name = "replica-upload-api"
main = "src/index.ts"
compatibility_date = "2025-12-03"
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "replica-studio"

# 環境変数
[vars]
PUBLIC_URL = "https://pub-281c2c3269ed42ebb12a315a950dc16c.r2.dev"