services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    platform: linux/amd64net
    env_file:
      - .env
    volumes:
      - ./backend:./backend
    command: 
      - gunicorn config.wsgi:application --bind 0.0.0.0:8000 --timeout 120 --workers  3
    container_name: backend
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    depends_on:
      - replica-db
    networks:
      - replica_networks
  
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    platform: linux/amd64
    container_name: frontend
    command: "npm run dev"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:./frontend
      - /frontend/node_modules
    ports:
      - 3000:3000
    networks:
      - replica_networks

  replica-db:
    image: postgres:16
    container_name: replica-db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: replica
      POSTGRES_USER: takato
      POSTGRES_PASSWORD: 20050605
    networks:
      - replica_networks
    
  nginx:
    build: ./nginx
    container_name: replica-nginx
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
    networks:
      - replica_networks
volumes:
  postgres_data
networks:
  replica_networks